Docker for RpmGrill
-------------------
:toc:

This repository contains docker files relating to RpmGrill.

Image Reference
---------------
base::
    `base` directory contains minimal changes common to `Fedora` and `CentOS`
    images. They contain minimal set of tools like git, vim needed by all
    other images. It also creates a default user is `dev` and has `sudo`
    privileges. So that during development, one can ensure that tests run as
    normal user and when needed can install new packages without exiting
    the container.

devenv::
    `devenv` directory contains development environments for various supported
    distros. These images are built on top of `base` images . They contain all
    dependencies needed to run RpmGrill and its tests.

Building Images
~~~~~~~~~~~~~~~~

Uses `docker-compose` to build docker images. To build the images install
latest docker-compose and run `docker-compose -p build`

[source,bash]
----
$ pip install --user -U docker-compose

$ cd <project-dir>/dev-tools/docker/
$ docker-compose -p rpmgrill build
----

Individual images can be built as well. For e.g to build `f20` image

[source,bash]
----
$ docker-compose -p rpmgrill build f20
----

NOTE: you can use `-p` option with docker-compose to provide a project name.
For e.g. `docker-compose -p rpmgrill build`

Using images
~~~~~~~~~~~~
Use docker-compose `run` to use docker image.

[source, bash]
----
$ docker-compose -p rpmgrill run f20 bash
----

To open another session use `docker exec`

[source, bash]
----
$ docker-compose ps
# NOTE the container id something like: docker_f20_run_1
$ docker exec -it docker_f20_run_1 bash
----

Preserve history
~~~~~~~~~~~~~~~~
To preserve bash or zsh history, consider mounting a directory on host as
`home/dev/`. For this, change the `docker-compose.yml` files `f21` entry to
look like the one below. Now the history will be wr

[source,txt]
----
f21: &devenv
  build: devenv/f21
  privileged: true
  user: 1000
  volumes:
    - &code  ../../:/code
    - &projectdir ../../../:/project
    - &homedir ~/docker/<rpmgrill>/home/:/home/dev
----
