# autogenerated specfile
Summary: Dummy summary
Name: librpmgrill
Version: 1.2.3
Release: 2.fc25
License: GPL
Group: Applications/Productivity

BuildRoot: %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)
Source0: librpmgrill.8
Patch0: change_unpack.patch

%description
This is a dummy description.

%prep
cp %{SOURCE0} .

%build

%clean
rm -rf $$RPM_BUILD_ROOT
%install
rm -rf $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/%{_datadir}/man/man8
cp %{SOURCE0} $RPM_BUILD_ROOT/%{_datadir}/man/man8/librpmgrill.8.gz
chmod 0755 $RPM_BUILD_ROOT/%{_datadir}/man/man8/librpmgrill.8.gz
mkdir -p $RPM_BUILD_ROOT//usr/share
echo "The value of RPM_OPT_FLAGS during the build is: $RPM_OPT_FLAGS"  > $RPM_BUILD_ROOT//usr/share/bogusly-arch-specific-data.txt
echo "The value of RPM_ARCH during the build is: $RPM_ARCH"  >> $RPM_BUILD_ROOT//usr/share/bogusly-arch-specific-data.txt

%files
%doc "/%{_datadir}/man/man8/librpmgrill.8.gz"
//usr/share/bogusly-arch-specific-data.txt

%changelog
* Thu Apr 31 2017 Roman Joost <rjoost@redhat.com> 1.2.3-3
- bogus entry
